name: Test and Publish to Pypi

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: Install Icarus Verilog
        run: |
          sudo apt-get -y update
          sudo apt-get -y install iverilog
      - name: Run tox
        run: uv run tox

  publish:
    name: Publish on Pypi
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nortl
    permissions:
      id-token: write
      contents: read

    # Only publish to PyPi on tag pushes
    if: github.ref_type == 'tag'

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: Build Project
        run: uv build
      - name: Publish on Pypi
        run: uv publish
